/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideosIndexRouteImport } from './routes/videos/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VideosUploadRouteImport } from './routes/videos/upload'
import { Route as VideosIdRouteImport } from './routes/videos/$id'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiVideosIndexRouteImport } from './routes/api/videos/index'
import { Route as ApiVideosUploadRouteImport } from './routes/api/videos/upload'
import { Route as ApiVideosIdRouteImport } from './routes/api/videos/$id'
import { Route as ApiVideosIdProgressRouteImport } from './routes/api/videos/$id/progress'
import { Route as ApiVideosIdFrameFilenameRouteImport } from './routes/api/videos/$id/frame/$filename'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosUploadRoute = VideosUploadRouteImport.update({
  id: '/videos/upload',
  path: '/videos/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIdRoute = VideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosIndexRoute = ApiVideosIndexRouteImport.update({
  id: '/api/videos/',
  path: '/api/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosUploadRoute = ApiVideosUploadRouteImport.update({
  id: '/api/videos/upload',
  path: '/api/videos/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosIdRoute = ApiVideosIdRouteImport.update({
  id: '/api/videos/$id',
  path: '/api/videos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideosIdProgressRoute = ApiVideosIdProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ApiVideosIdRoute,
} as any)
const ApiVideosIdFrameFilenameRoute =
  ApiVideosIdFrameFilenameRouteImport.update({
    id: '/frame/$filename',
    path: '/frame/$filename',
    getParentRoute: () => ApiVideosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/workbench': typeof WorkbenchRoute
  '/api/events': typeof ApiEventsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/videos/$id': typeof VideosIdRoute
  '/videos/upload': typeof VideosUploadRoute
  '/blog/': typeof BlogIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/videos/$id': typeof ApiVideosIdRouteWithChildren
  '/api/videos/upload': typeof ApiVideosUploadRoute
  '/api/videos/': typeof ApiVideosIndexRoute
  '/api/videos/$id/progress': typeof ApiVideosIdProgressRoute
  '/api/videos/$id/frame/$filename': typeof ApiVideosIdFrameFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/workbench': typeof WorkbenchRoute
  '/api/events': typeof ApiEventsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/videos/$id': typeof VideosIdRoute
  '/videos/upload': typeof VideosUploadRoute
  '/blog': typeof BlogIndexRoute
  '/videos': typeof VideosIndexRoute
  '/api/videos/$id': typeof ApiVideosIdRouteWithChildren
  '/api/videos/upload': typeof ApiVideosUploadRoute
  '/api/videos': typeof ApiVideosIndexRoute
  '/api/videos/$id/progress': typeof ApiVideosIdProgressRoute
  '/api/videos/$id/frame/$filename': typeof ApiVideosIdFrameFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/workbench': typeof WorkbenchRoute
  '/api/events': typeof ApiEventsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/videos/$id': typeof VideosIdRoute
  '/videos/upload': typeof VideosUploadRoute
  '/blog/': typeof BlogIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/api/videos/$id': typeof ApiVideosIdRouteWithChildren
  '/api/videos/upload': typeof ApiVideosUploadRoute
  '/api/videos/': typeof ApiVideosIndexRoute
  '/api/videos/$id/progress': typeof ApiVideosIdProgressRoute
  '/api/videos/$id/frame/$filename': typeof ApiVideosIdFrameFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/rss.xml'
    | '/workbench'
    | '/api/events'
    | '/blog/$slug'
    | '/demo/drizzle'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/videos/$id'
    | '/videos/upload'
    | '/blog/'
    | '/videos/'
    | '/api/videos/$id'
    | '/api/videos/upload'
    | '/api/videos/'
    | '/api/videos/$id/progress'
    | '/api/videos/$id/frame/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/rss.xml'
    | '/workbench'
    | '/api/events'
    | '/blog/$slug'
    | '/demo/drizzle'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/videos/$id'
    | '/videos/upload'
    | '/blog'
    | '/videos'
    | '/api/videos/$id'
    | '/api/videos/upload'
    | '/api/videos'
    | '/api/videos/$id/progress'
    | '/api/videos/$id/frame/$filename'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/rss.xml'
    | '/workbench'
    | '/api/events'
    | '/blog/$slug'
    | '/demo/drizzle'
    | '/demo/store'
    | '/demo/tanstack-query'
    | '/videos/$id'
    | '/videos/upload'
    | '/blog/'
    | '/videos/'
    | '/api/videos/$id'
    | '/api/videos/upload'
    | '/api/videos/'
    | '/api/videos/$id/progress'
    | '/api/videos/$id/frame/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  WorkbenchRoute: typeof WorkbenchRoute
  ApiEventsRoute: typeof ApiEventsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  VideosIdRoute: typeof VideosIdRoute
  VideosUploadRoute: typeof VideosUploadRoute
  BlogIndexRoute: typeof BlogIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  ApiVideosIdRoute: typeof ApiVideosIdRouteWithChildren
  ApiVideosUploadRoute: typeof ApiVideosUploadRoute
  ApiVideosIndexRoute: typeof ApiVideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/upload': {
      id: '/videos/upload'
      path: '/videos/upload'
      fullPath: '/videos/upload'
      preLoaderRoute: typeof VideosUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$id': {
      id: '/videos/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof VideosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/': {
      id: '/api/videos/'
      path: '/api/videos'
      fullPath: '/api/videos/'
      preLoaderRoute: typeof ApiVideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/upload': {
      id: '/api/videos/upload'
      path: '/api/videos/upload'
      fullPath: '/api/videos/upload'
      preLoaderRoute: typeof ApiVideosUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/$id': {
      id: '/api/videos/$id'
      path: '/api/videos/$id'
      fullPath: '/api/videos/$id'
      preLoaderRoute: typeof ApiVideosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/videos/$id/progress': {
      id: '/api/videos/$id/progress'
      path: '/progress'
      fullPath: '/api/videos/$id/progress'
      preLoaderRoute: typeof ApiVideosIdProgressRouteImport
      parentRoute: typeof ApiVideosIdRoute
    }
    '/api/videos/$id/frame/$filename': {
      id: '/api/videos/$id/frame/$filename'
      path: '/frame/$filename'
      fullPath: '/api/videos/$id/frame/$filename'
      preLoaderRoute: typeof ApiVideosIdFrameFilenameRouteImport
      parentRoute: typeof ApiVideosIdRoute
    }
  }
}

interface ApiVideosIdRouteChildren {
  ApiVideosIdProgressRoute: typeof ApiVideosIdProgressRoute
  ApiVideosIdFrameFilenameRoute: typeof ApiVideosIdFrameFilenameRoute
}

const ApiVideosIdRouteChildren: ApiVideosIdRouteChildren = {
  ApiVideosIdProgressRoute: ApiVideosIdProgressRoute,
  ApiVideosIdFrameFilenameRoute: ApiVideosIdFrameFilenameRoute,
}

const ApiVideosIdRouteWithChildren = ApiVideosIdRoute._addFileChildren(
  ApiVideosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  WorkbenchRoute: WorkbenchRoute,
  ApiEventsRoute: ApiEventsRoute,
  BlogSlugRoute: BlogSlugRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  VideosIdRoute: VideosIdRoute,
  VideosUploadRoute: VideosUploadRoute,
  BlogIndexRoute: BlogIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  ApiVideosIdRoute: ApiVideosIdRouteWithChildren,
  ApiVideosUploadRoute: ApiVideosUploadRoute,
  ApiVideosIndexRoute: ApiVideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
